services:
  traefik:
    image: traefik:latest
    container_name: solv_traefik
    environment:
      - DOCKER_API_VERSION=1.41
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3=true" 
      - "--api.insecure=true" 
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
      - "./infra/traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro"
    networks:
      - solv_net

  postgres:
    image: postgres:18-alpine
    container_name: solv_db
    environment:
      POSTGRES_USER: solv_user
      POSTGRES_PASSWORD: solv_password
      POSTGRES_DB: solv_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - solv_net
    # Aislado de Traefik (Sin labels, no expuesto a la web)

networks:
  solv_net:
    name: solv_net
    driver: bridge

volumes:
  pg_data:
