services:
  traefik:
    image: traefik:v3.1.2
    container_name: solv_traefik
    environment:
      - DOCKER_API_VERSION=1.41
      - DESEC_TOKEN=${DESEC_TOKEN}
      - DESEC_API_BASE_URL=https://desec.io/api/v1/
      - ACME_EMAIL=${ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./infra/traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro"
      - "./letsencrypt/acme.json:/letsencrypt/acme.json"
    networks:
      - solv_net

  postgres:
    image: postgres:18-alpine
    container_name: solv_db
    environment:
      POSTGRES_USER: solv_user
      POSTGRES_PASSWORD: solv_password
      POSTGRES_DB: solv_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - solv_net

  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: solv_prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - solv_net

  grafana:
    image: grafana/grafana:10.4.1
    container_name: solv_grafana
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - solv_net

networks:
  solv_net:
    name: solv_net
    driver: bridge

volumes:
  pg_data:
